export { Home } from './Home'
export { About } from './About'
export { Experience } from './Experience'
export { Projects } from './Projects'
export { Skills } from './Skills'
export { Certifications } from './Certifications'
export { Education } from './Education'
export { Contact } from './Contact'
